# Edit to match YOUR machine. This file IS git-tracked,
# but each team member has their own local edits.

raw_data_dir: C:/Users/naqee/OneDrive/Desktop/CSC415 Project/data
unified_data_dir: C:/Users/naqee/OneDrive/Desktop/CSC415 Project/data/unified
robomimic_raw: C:/Users/naqee/OneDrive/Desktop/CSC415 Project/data/robomimic
rlbench_raw: C:/Users/naqee/OneDrive/Desktop/CSC415 Project/data/rlbench
maniskill_raw: C:/Users/naqee/OneDrive/Desktop/CSC415 Project/data/maniskill
